### PR TITLE
Added --allow-not-run-notebook option

### PR DESCRIPTION
**Pull request by mepland**
Added `--allow-not-run-notebook` option

Allow notebooks with only unrun cells to pass.

### CODE REVIEW

**Comment by mepland** [comment]
@christopher-hacker I did not update the README yet. Please let me know if you like the `--allow-not-run-notebook` flag and intend to merge this PR first, then I'd be happy to add a README section.

**Comment by jamesmyatt** [comment]
I think this should be the default behaviour, so I don't think this needs to be an option. But it should probably check that the outputs are empty when the execution_count is None.

**Comment by mepland** [comment]
@christopher-hacker can we wrap up  this PR?

**Comment by mepland** [comment]
Note https://github.com/christopher-hacker/enforce-notebook-run-order/issues/13 is related

**Comment by christopher-hacker** [comment]
On deadline at work right now, but will try to clear this up this week. My plan is to make this the default behavior per @jamesmyatt's suggestion, and will clear up #13 as well.

**Comment by christopher-hacker** [comment]
This is now the default behavior for all empty cells, per #16

**Pull request closed without merging**
